// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package jsonwebtoken.actions;

import com.auth0.jwt.JWT;
import com.auth0.jwt.JWTVerifier;
import com.auth0.jwt.exceptions.JWTVerificationException;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import jsonwebtoken.helper.AlgorithmHelper;

public class JA_VerifyToken extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String token;
	private java.lang.String secret;
	private jsonwebtoken.proxies.Enum_Algorithm algorithm;

	public JA_VerifyToken(IContext context, java.lang.String token, java.lang.String secret, java.lang.String algorithm)
	{
		super(context);
		this.token = token;
		this.secret = secret;
		this.algorithm = algorithm == null ? null : jsonwebtoken.proxies.Enum_Algorithm.valueOf(algorithm);
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		String logNode = jsonwebtoken.proxies.constants.Constants.getLogNode();
		
		// Check if algorithm has been provided
		if (this.algorithm == null) {
			Core.getLogger(logNode).warn("No valid algorithm has been provided");
			return false;
		}
		
		// Try to verify token
		try {
		    JWTVerifier verifier = JWT.require(AlgorithmHelper.Algorithm(this.algorithm, this.secret))
		        .build();
		    
		    // Verify token
		    verifier.verify(this.token);
		} catch (JWTVerificationException exception){
			// Token was invalid, return false
		    return false;
		}
		
		// No exception has been thrown, so token was valid
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "JA_VerifyToken";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
