// This file was generated by Mendix Modeler 7.10.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package jsonwebtoken.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the JSONWebToken module

	public static java.lang.String getLogNode()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("JSONWebToken.LogNode");
	}
}