// This file was generated by Mendix Modeler 7.10.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mendixblockchain.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the MendixBlockchain module

	public static java.lang.String getZeros()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MendixBlockchain.Zeros");
	}
}