// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mendixblockchain.actions;

import java.util.Iterator;
import java.util.Map;
import com.mendix.core.objectmanagement.member.MendixBoolean;
import com.mendix.core.objectmanagement.member.MendixDateTime;
import com.mendix.core.objectmanagement.member.MendixInteger;
import com.mendix.core.objectmanagement.member.MendixLong;
import com.mendix.core.objectmanagement.member.MendixString;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IMendixObjectMember;
import com.mendix.webui.CustomJavaAction;

public class GetMembersConcatted extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __IteratorBlock;
	private mendixblockchain.proxies.Transaction IteratorBlock;

	public GetMembersConcatted(IContext context, IMendixObject IteratorBlock)
	{
		super(context);
		this.__IteratorBlock = IteratorBlock;
	}

	@Override
	public java.lang.String executeAction() throws Exception
	{
		this.IteratorBlock = __IteratorBlock == null ? null : mendixblockchain.proxies.Transaction.initialize(getContext(), __IteratorBlock);

		// BEGIN USER CODE
		Map<String, ? extends IMendixObjectMember<?>> mp = this.__IteratorBlock.getMembers(getContext());
		String concatted = "";
		Iterator it = mp.entrySet().iterator();
		for (Map.Entry<String, ? extends IMendixObjectMember<?>> pair : mp.entrySet()) {
			
			if(pair.getKey().equals("Signature") || pair.getKey().equals("Data")) {
				continue;
			}
			
	        Object value = pair.getValue();
	        if(value instanceof MendixString) 
	        	concatted += ((MendixString)value).getValue(this.getContext());
	        if(value instanceof MendixDateTime) 
	        	concatted += ((MendixDateTime)value).getValue(this.getContext());
	        if(value instanceof MendixLong) 
	        	concatted += ((MendixLong)value).getValue(this.getContext());
	        if(value instanceof MendixInteger ) 
	        	concatted += ((MendixInteger)value).getValue(this.getContext());
	        
	    }
	    return concatted;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetMembersConcatted";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
