// This file was generated by Mendix Modeler 7.10.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package jsonwebtoken.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the JSONWebToken module
	public static void mB_GenerateToken(IContext context, jsonwebtoken.proxies.Token _token)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Token", _token == null ? null : _token.getMendixObject());
			Core.execute(context, "JSONWebToken.MB_GenerateToken", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_Token_New(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "JSONWebToken.MB_Token_New", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sUB_DecodeSingleClaim(IContext context, java.lang.String _tokenString, java.lang.String _secret, java.lang.String _claimName, jsonwebtoken.proxies.Enum_Algorithm _algorithm)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("TokenString", _tokenString);
			params.put("Secret", _secret);
			params.put("ClaimName", _claimName);
			params.put("Algorithm", _algorithm == null ? null : _algorithm.name());
			Core.execute(context, "JSONWebToken.SUB_DecodeSingleClaim", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sUB_DecodeToken(IContext context, java.lang.String _tokenString, java.lang.String _secret, jsonwebtoken.proxies.Enum_Algorithm _algorithm)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("TokenString", _tokenString);
			params.put("Secret", _secret);
			params.put("Algorithm", _algorithm == null ? null : _algorithm.name());
			Core.execute(context, "JSONWebToken.SUB_DecodeToken", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sUB_VerifyToken(IContext context, java.lang.String _tokenString, java.lang.String _secret, jsonwebtoken.proxies.Enum_Algorithm _algorithm)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("TokenString", _tokenString);
			params.put("Secret", _secret);
			params.put("Algorithm", _algorithm == null ? null : _algorithm.name());
			Core.execute(context, "JSONWebToken.SUB_VerifyToken", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}